FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

RUN npm install -g wrangler

COPY package*.json ./
COPY tsconfig*.json ./
COPY .wrangler/ ./.wrangler/
COPY src/ ./src/

RUN npm ci --omit=dev

EXPOSE 8787

CMD ["npx", "wrangler", "dev", "--port", "8787", "--host", "0.0.0.0"]