// StudyPilot Library seeder.
//
// Curated, admin-authored decks are stored in `library_decks` + `library_cards`.
// This script builds a fully idempotent SQL file (INSERT OR IGNORE + per-card
// guards keyed by deck name + front text) so re-runs are safe, then applies it
// via `wrangler d1 execute` against the configured database.
//
// Usage:
//   node scripts/seed-library.mjs            # emit ./scripts/seed-library.sql only
//   node scripts/seed-library.mjs --local    # apply to local D1
//   node scripts/seed-library.mjs --remote   # apply to remote D1
//
// Requires wrangler + the D1 binding "mednexus-db" (see wrangler.toml).

import { writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";

const DB = "mednexus-db";

// ── Curated content ──────────────────────────────────────────────────────────
// Each card: { front, back, topics:[], difficulty:'easy'|'medium'|'hard' }
// `ai*` fields are omitted for heuristic-sourced cards.
const DECK_RE = /'/g;
const esc = (s) => String(s).replace(DECK_RE, "''");

const decks = [
  {
    name: "Spanish Basics",
    description: "Essential Spanish vocabulary and phrases for beginners.",
    category: "Languages",
    difficulty: "easy",
    cards: [
      { front: "Hello", back: "Hola", topics: ["greetings"], difficulty: "easy" },
      { front: "Goodbye", back: "Adiós", topics: ["greetings"], difficulty: "easy" },
      { front: "Please", back: "Por favor", topics: ["courtesy"], difficulty: "easy" },
      { front: "Thank you", back: "Gracias", topics: ["courtesy"], difficulty: "easy" },
      { front: "How are you?", back: "¿Cómo estás?", topics: ["greetings"], difficulty: "medium" },
      { front: "I would like water", back: "Quisiera agua", topics: ["food"], difficulty: "medium" },
      { front: "Where is the bathroom?", back: "¿Dónde está el baño?", topics: ["travel"], difficulty: "hard" },
    ],
  },
  {
    name: "Intro to Python",
    description: "Core Python programming concepts for first-time coders.",
    category: "Programming",
    difficulty: "medium",
    cards: [
      { front: "What does the `print()` function do?", back: "Outputs text/values to the console.", topics: ["functions"], difficulty: "easy" },
      { front: "How do you define a list?", back: "Using square brackets: `my_list = [1, 2, 3]`.", topics: ["data-structures"], difficulty: "easy" },
      { front: "What is a for loop?", back: "Iterates over a sequence, executing a block once per item.", topics: ["loops"], difficulty: "medium" },
      { front: "What is list comprehension?", back: "A concise way to create lists: `[x*2 for x in nums]`.", topics: ["data-structures"], difficulty: "hard" },
      { front: "How do you define a function?", back: "Use `def name(args):` followed by an indented body.", topics: ["functions"], difficulty: "medium" },
      { front: "What does `len()` return?", back: "The number of items in a collection.", topics: ["builtins"], difficulty: "easy" },
    ],
  },
  {
    name: "Biology 101",
    description: "Foundational biology terms covering cells, genetics, and ecology.",
    category: "Science",
    difficulty: "medium",
    cards: [
      { front: "What is the powerhouse of the cell?", back: "The mitochondrion.", topics: ["cells"], difficulty: "easy" },
      { front: "Define photosynthesis.", back: "Process where plants convert light, CO₂, and water into glucose and oxygen.", topics: ["cells"], difficulty: "medium" },
      { front: "What is DNA?", back: "Deoxyribonucleic acid — carries genetic instructions.", topics: ["genetics"], difficulty: "easy" },
      { front: "What is mitosis?", back: "Cell division producing two identical diploid daughter cells.", topics: ["genetics"], difficulty: "hard" },
      { front: "What is an ecosystem?", back: "A community of organisms interacting with their physical environment.", topics: ["ecology"], difficulty: "medium" },
      { front: "Define osmosis.", back: "Movement of water across a semipermeable membrane from low to high solute concentration.", topics: ["cells"], difficulty: "hard" },
    ],
  },
];

// ── Build idempotent SQL ──────────────────────────────────────────────────────
const lines = [
  "-- StudyPilot library seed (idempotent). Generated by scripts/seed-library.mjs.",
  "-- NOTE: no BEGIN/COMMIT — D1 `wrangler d1 execute` rejects transaction statements.",
];

for (const d of decks) {
  const name = esc(d.name);
  const description = esc(d.description || "");
  const category = esc(d.category || "general");
  const tags = esc((d.cards.flatMap((c) => c.topics || []).filter(Boolean).join(",")));
  const difficulty = esc(d.difficulty || "medium");
  const cardCount = d.cards.length;

  // INSERT OR IGNORE relies on the UNIQUE(name) constraint — safe on re-run.
  lines.push(
    `INSERT OR IGNORE INTO library_decks (name, description, category, tags, difficulty, card_count) ` +
      `VALUES ('${name}', '${description}', '${category}', '${tags}', '${difficulty}', ${cardCount});`
  );

  for (const c of d.cards) {
    const front = esc(c.front);
    const back = esc(c.back);
    const ctags = esc((c.topics || []).join(","));
    const cdiff = esc(c.difficulty || d.difficulty || "medium");
    const source = esc(c.source || "heuristic");
    // Attach each card to the (possibly pre-existing) deck by name; skip if the
    // exact front text already exists for that deck.
    lines.push(
      `INSERT INTO library_cards (library_deck_id, front, back, tags, card_type, difficulty, source) ` +
        `SELECT id, '${front}', '${back}', '${ctags}', 'basic', '${cdiff}', '${source}' ` +
        `FROM library_decks WHERE name = '${name}' ` +
        `AND NOT EXISTS (SELECT 1 FROM library_cards lc WHERE lc.library_deck_id = library_decks.id AND lc.front = '${front}');`
    );
  }
}

const sql = lines.join("\n") + "\n";
const outPath = new URL("./seed-library.sql", import.meta.url);
writeFileSync(outPath, sql);
console.log(`Wrote ${outPath.pathname} (${decks.length} decks, ${decks.reduce((n, d) => n + d.cards.length, 0)} cards).`);

// ── Apply (optional) ──────────────────────────────────────────────────────────
const mode = process.argv[2];
if (mode === "--local" || mode === "--remote") {
  const arg = mode === "--local" ? "--local" : "";
  console.log(`Applying to D1 (${mode})...`);
  execFileSync(
    "npx",
    ["wrangler", "d1", "execute", DB, arg, "--file", outPath.pathname].filter(Boolean),
    { stdio: "inherit" }
  );
} else {
  console.log("Pass --local or --remote to apply. Skipping apply.");
}
